name: CI - Build & Push Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      # Etapa opcional: verificar se o Python e dependências estão OK
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "Nenhum requirements.txt encontrado"
          fi

      - name: Rodar testes (opcional)
        run: |
          if [ -f tests/test_app.py ]; then
            pytest -v || echo "Falha nos testes"
          else
            echo "Nenhum teste encontrado. Pulando etapa."
          fi

      # Define nome e tag da imagem
      - name: Set image tags
        id: vars
        run: |
          echo "IMAGE=rhdd1/monitor" >> $GITHUB_OUTPUT
          echo "TAG_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push da imagem
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.vars.outputs.IMAGE }}:latest
            ${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.TAG_SHA }}
          cache-from: type=registry,ref=${{ steps.vars.outputs.IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ steps.vars.outputs.IMAGE }}:buildcache,mode=max
